//
// Created by droc101 on 7/18/25.
//

#include <array>
#include <assimp/Importer.hpp>
#include <assimp/mesh.h>
#include <assimp/postprocess.h>
#include <assimp/scene.h>
#include <cstddef>
#include <cstdint>
#include <format>
#include <fstream>
#include <libassets/type/ModelLod.h>
#include <libassets/type/ModelVertex.h>
#include <libassets/util/DataReader.h>
#include <libassets/util/DataWriter.h>
#include <libassets/util/Error.h>
#include <libassets/util/Logger.h>
#include <numeric>
#include <string>
#include <unordered_map>
#include <vector>

#define STB_RECT_PACK_IMPLEMENTATION
#include <glm/ext/vector_common.hpp>
#include <glm/geometric.hpp>
#include <stb_rect_pack.h>

#include "../../../mapcomp/LevelMeshBuilder.h"

ModelLod::ModelLod(DataReader &reader, const uint32_t materialsPerSkin)
{
    distance = reader.Read<float>();
    reader.Skip<float>();
    const size_t vertexCount = reader.Read<size_t>();
    for (size_t _i = 0; _i < vertexCount; _i++)
    {
        vertices.emplace_back(reader);
    }
    reader.Skip<uint32_t>(); // Skips the total index count which is not needed for editing
    for (uint32_t _i = 0; _i < materialsPerSkin; _i++)
    {
        indexCounts.push_back(reader.Read<uint32_t>());
    }
    for (const uint32_t indexCount: indexCounts)
    {
        std::vector<uint32_t> indices;
        for (size_t _i = 0; _i < indexCount; _i++)
        {
            indices.push_back(reader.Read<uint32_t>());
        }
        materialIndices.push_back(indices);
    }
}

ModelLod::ModelLod(const std::string &filePath, const float distance, Error::ErrorCode &status)
{
    this->distance = distance;

    std::unordered_map<ModelVertex, uint32_t> vertexToIndex;

    Assimp::Importer importer{};
    constexpr uint32_t IMPORT_FLAGS = aiProcess_Triangulate |
                                      aiProcess_JoinIdenticalVertices |
                                      aiProcess_SortByPType |
                                      aiProcess_ValidateDataStructure |
                                      aiProcess_GenNormals;
    const aiScene *scene = importer.ReadFile(filePath, IMPORT_FLAGS);

    if (scene == nullptr || (scene->mFlags & AI_SCENE_FLAGS_INCOMPLETE) != 0u || scene->mRootNode == nullptr)
    {
        Logger::Error("Assimp error: {}", importer.GetErrorString());
        status = Error::ErrorCode::UNKNOWN;
        return;
    }

    for (uint32_t i = 0; i < scene->mNumMeshes; i++)
    {
        const aiMesh *mesh = scene->mMeshes[i];
        const uint32_t materialIndex = mesh->mMaterialIndex;

        if (materialIndex >= materialIndices.size())
        {
            materialIndices.resize(materialIndex + 1);
        }

        std::vector<uint32_t> &indices = materialIndices.at(materialIndex);

        for (uint32_t j = 0; j < mesh->mNumFaces; j++)
        {
            const aiFace &face = mesh->mFaces[j];
            for (uint32_t k = 0; k < face.mNumIndices; k++)
            {
                const uint32_t vertexIndex = face.mIndices[k];
                const ModelVertex vertex(mesh, vertexIndex);
                if (vertexToIndex.contains(vertex))
                {
                    indices.push_back(vertexToIndex.at(vertex));
                } else
                {
                    indices.push_back(this->vertices.size());
                    this->vertices.push_back(vertex);
                    vertexToIndex[vertex] = indices.back();
                }
            }
        }
    }

    std::vector<int64_t> toErase{};
    for (uint32_t i = 0; i < materialIndices.size(); i++)
    {
        const std::vector<uint32_t> &indices = materialIndices.at(i);
        if (indices.size() < 3) // check for materials with no triangles
        {
            toErase.push_back(i);
        }
        indexCounts.push_back(indices.size());
    }

    for (const int64_t &index: toErase)
    {
        materialIndices.erase(materialIndices.begin() + index);
        indexCounts.erase(indexCounts.begin() + index);
    }

    status = Error::ErrorCode::OK;
}

void ModelLod::Export(const char *path) const
{
    std::ofstream file(path);
    file << "# Generated by GAME SDK\n\n";
    for (const ModelVertex &vertex: vertices)
    {
        std::array<float, 4> color = vertex.color.CopyData();
        file << std::format("v {} {} {} {} {} {} {}\n",
                            vertex.position.x,
                            vertex.position.y,
                            vertex.position.z,
                            color.at(0),
                            color.at(1),
                            color.at(2),
                            color.at(3));
        file << std::format("vt {} {}\n", vertex.uv.x, vertex.uv.y);
        file << std::format("vn {} {} {}\n", vertex.normal.x, vertex.normal.y, vertex.normal.z);
    }

    file << "\n\n";

    for (size_t m = 0; m < materialIndices.size(); m++)
    {
        file << std::format("usemtl mat_{}\n", m);
        for (uint32_t i = 0; i < indexCounts.at(m); i += 3)
        {
            const uint32_t index0 = materialIndices.at(m).at(i + 0) + 1;
            const uint32_t index1 = materialIndices.at(m).at(i + 1) + 1;
            const uint32_t index2 = materialIndices.at(m).at(i + 2) + 1;
            file << std::format("f {0}/{0}/{0} {1}/{1}/{1} {2}/{2}/{2}\n", index0, index1, index2);
        }
        file << "\n";
    }

    file.close();
}

void ModelLod::Write(DataWriter &writer) const
{
    writer.Write<float>(distance);
    writer.Write<float>(distance * distance);
    writer.Write<size_t>(vertices.size());
    for (const ModelVertex &vertex: vertices)
    {
        vertex.Write(writer);
    }
    const uint32_t totalIndexCount = std::accumulate(indexCounts.begin(), indexCounts.end(), 0ul);
    writer.Write<uint32_t>(totalIndexCount);
    writer.WriteBuffer<uint32_t>(indexCounts);
    for (const std::vector<uint32_t> &lodIndices: materialIndices)
    {
        writer.WriteBuffer<uint32_t>(lodIndices);
    }
}

bool ModelLod::CalculateLightmapUvs()
{
    std::vector<stbrp_rect> rects{};
    assert(indexCounts.size() == materialIndices.size());
    for (uint32_t materialSlotIndex = 0; materialSlotIndex < indexCounts.size(); materialSlotIndex++)
    {
        const uint32_t indexCount = indexCounts.at(materialSlotIndex);
        const std::vector<uint32_t> &indices = materialIndices.at(materialSlotIndex);
        for (uint32_t i = 0; i < indexCount; i += 3)
        {
            const glm::vec3 &v1 = vertices.at(indices.at(i + 0)).position;
            const glm::vec3 &v2 = vertices.at(indices.at(i + 1)).position;
            const glm::vec3 &v3 = vertices.at(indices.at(i + 2)).position;

            const float a = glm::distance(v1, v2);
            const float b = glm::distance(v1, v3);
            const float c = glm::distance(v2, v3);

            rects.emplace_back(0,
                               2 * LevelMeshBuilder::LIGHTMAP_PADDING + std::max(c, (b * b + c * c - a * a) / (2 * c)),
                               2 * LevelMeshBuilder::LIGHTMAP_PADDING +
                                       b * std::sin(std::acosf((b * b + c * c - a * a) / (2 * b * c))));
        }
    }


    int width = 128;
    int height = 128;
    stbrp_context context{};
    bool wasHeightChangedLast = false;
    constexpr int MAX_LIGHTMAP_SIZE = 1 << 14;
    std::vector<stbrp_node> nodes{};
    while (true)
    {
        nodes.clear();
        nodes.resize(width * 2);
        stbrp_init_target(&context, width, height, nodes.data(), static_cast<int>(nodes.size()));

        if (stbrp_pack_rects(&context, rects.data(), static_cast<int>(rects.size())) == 0)
        {
            if (width == MAX_LIGHTMAP_SIZE && height == MAX_LIGHTMAP_SIZE)
            {
                return false;
            }
            if (wasHeightChangedLast)
            {
                width = width << 1;
                wasHeightChangedLast = false;
            } else
            {
                height = height << 1;
                wasHeightChangedLast = true;
            }
        } else
        {
            break;
        }
    }

    for (uint32_t materialSlotIndex = 0; materialSlotIndex < indexCounts.size(); materialSlotIndex++)
    {
        const uint32_t indexCount = indexCounts.at(materialSlotIndex);
        const std::vector<uint32_t> &indices = materialIndices.at(materialSlotIndex);
        for (uint32_t i = 0; i < indexCount; i += 3)
        {
            const stbrp_rect &rect = rects.at(i / 3);

            ModelVertex &v1 = vertices.at(indices.at(i + 0));
            ModelVertex &v2 = vertices.at(indices.at(i + 1));
            ModelVertex &v3 = vertices.at(indices.at(i + 2));

            const float a = glm::distance(v1.position, v2.position);
            const float b = glm::distance(v1.position, v3.position);
            const float c = glm::distance(v2.position, v3.position);

            v1.lightmapUv.x = static_cast<float>(rect.x + LevelMeshBuilder::LIGHTMAP_PADDING) /
                              static_cast<float>(width);
            v1.lightmapUv.y = static_cast<float>(rect.y + LevelMeshBuilder::LIGHTMAP_PADDING) /
                              static_cast<float>(height);
            v2.lightmapUv.x = (static_cast<float>(rect.x + LevelMeshBuilder::LIGHTMAP_PADDING) +
                               c * static_cast<float>(rect.w - 2 * LevelMeshBuilder::LIGHTMAP_PADDING)) /
                              static_cast<float>(width);
            v2.lightmapUv.y = v1.lightmapUv.y;
            v2.lightmapUv.x = (static_cast<float>(rect.x + LevelMeshBuilder::LIGHTMAP_PADDING) +
                               (b * b + c * c - a * a) /
                                       (2 * c) *
                                       static_cast<float>(rect.w - 2 * LevelMeshBuilder::LIGHTMAP_PADDING)) /
                              static_cast<float>(width);
            v3.lightmapUv.y = (static_cast<float>(rect.y + LevelMeshBuilder::LIGHTMAP_PADDING) +
                               b *
                                       std::sin(std::acosf((b * b + c * c - a * a) / (2 * b * c))) *
                                       static_cast<float>(rect.h - 2 * LevelMeshBuilder::LIGHTMAP_PADDING)) /
                              static_cast<float>(height);
        }
    }

    return true;
}

void ModelLod::FlipVerticalUVs()
{
    for (ModelVertex &v: vertices)
    {
        v.uv.y = 1.0f - v.uv.y;
    }
}
