//
// Created by droc101 on 7/18/25.
//

#include <array>
#include <assimp/Importer.hpp>
#include <assimp/mesh.h>
#include <assimp/postprocess.h>
#include <assimp/scene.h>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <format>
#include <fstream>
#include <glm/glm.hpp>
#include <libassets/type/ModelLod.h>
#include <libassets/type/ModelVertex.h>
#include <libassets/util/DataReader.h>
#include <libassets/util/DataWriter.h>
#include <libassets/util/Error.h>
#include <libassets/util/LightmapHelpers.hpp>
#include <libassets/util/Logger.h>
#include <numeric>
#include <stb_rect_pack.h>
#include <string>
#include <unordered_map>
#include <vector>

#include "libassets/type/BoundingBox.h"

ModelLod::ModelLod(DataReader &reader, const uint32_t componentCount)
{
    distance = reader.Read<float>();
    reader.Skip<float>();
    unitsPerLuxel = reader.Read<float>();
    lightmapSize.x = reader.Read<uint32_t>();
    lightmapSize.y = reader.Read<uint32_t>();
    const size_t vertexCount = reader.Read<size_t>();
    for (size_t _ = 0; _ < vertexCount; _++)
    {
        vertices.emplace_back(reader);
    }
    reader.Skip<uint32_t>(); // Skips the total index count which is not needed for editing
    for (uint32_t _ = 0; _ < componentCount; _++)
    {
        const uint32_t indexCount = reader.Read<uint32_t>();
        std::vector<uint32_t> indices;
        reader.ReadToVector<uint32_t>(indices, indexCount);
        const glm::vec3 centerOffset = reader.ReadVec3();
        const float radius = reader.Read<float>();
        components.emplace_back(std::move(indices), centerOffset, radius);
        totalIndexCount += indexCount;
    }
}

ModelLod::ModelLod(const std::string &filePath, const float distance, Error::ErrorCode &status)
{
    this->distance = distance;

    std::unordered_map<ModelVertex, uint32_t> vertexToIndex;

    Assimp::Importer importer{};
    constexpr uint32_t IMPORT_FLAGS = aiProcess_Triangulate |
                                      aiProcess_JoinIdenticalVertices |
                                      aiProcess_SortByPType |
                                      aiProcess_ValidateDataStructure |
                                      aiProcess_GenNormals;
    const aiScene *scene = importer.ReadFile(filePath, IMPORT_FLAGS);

    if (scene == nullptr || (scene->mFlags & AI_SCENE_FLAGS_INCOMPLETE) != 0u || scene->mRootNode == nullptr)
    {
        Logger::Error("Assimp error: {}", importer.GetErrorString());
        status = Error::ErrorCode::UNKNOWN;
        return;
    }

    for (uint32_t i = 0; i < scene->mNumMeshes; i++)
    {
        const aiMesh *mesh = scene->mMeshes[i];
        const uint32_t componentIndex = mesh->mMaterialIndex;

        if (componentIndex >= components.size())
        {
            components.resize(componentIndex + 1);
        }

        ModelComponent &component = components.at(componentIndex);

        for (uint32_t j = 0; j < mesh->mNumFaces; j++)
        {
            const aiFace &face = mesh->mFaces[j];
            for (uint32_t k = 0; k < face.mNumIndices; k++)
            {
                const uint32_t vertexIndex = face.mIndices[k];
                const ModelVertex vertex(mesh, vertexIndex);
                if (vertexToIndex.contains(vertex))
                {
                    component.indices.push_back(vertexToIndex.at(vertex));
                } else
                {
                    component.indices.push_back(this->vertices.size());
                    this->vertices.push_back(vertex);
                    vertexToIndex[vertex] = component.indices.back();
                }
            }
        }
    }

    std::erase_if(components, [](const ModelComponent &component) -> bool { return component.indices.size() < 3; });

    for (ModelComponent &component: components)
    {
        glm::vec3 minPoint{std::numeric_limits<float>::max()};
        glm::vec3 maxPoint{std::numeric_limits<float>::lowest()};
        for (const uint32_t index: component.indices)
        {
            minPoint = glm::min(minPoint, vertices.at(index).position);
            maxPoint = glm::max(maxPoint, vertices.at(index).position);
            totalIndexCount++;
        }
        component.centerOffset = (minPoint + maxPoint) * 0.5f;
        component.radius = glm::length((maxPoint - minPoint) * 0.5f);
    }

    status = Error::ErrorCode::OK;
}

void ModelLod::Export(const char *path) const
{
    std::ofstream file(path);
    file << "# Generated by GAME SDK\n\n";
    for (const ModelVertex &vertex: vertices)
    {
        std::array<float, 4> color = vertex.color.CopyData();
        file << std::format("v {} {} {} {} {} {} {}\n",
                            vertex.position.x,
                            vertex.position.y,
                            vertex.position.z,
                            color.at(0),
                            color.at(1),
                            color.at(2),
                            color.at(3));
        file << std::format("vt {} {}\n", vertex.uv.x, vertex.uv.y);
        file << std::format("vn {} {} {}\n", vertex.normal.x, vertex.normal.y, vertex.normal.z);
    }

    file << "\n\n";

    for (size_t m = 0; m < components.size(); m++)
    {
        file << std::format("usemtl mat_{}\n", m);
        const ModelComponent &component = components.at(m);
        for (uint32_t i = 0; i < component.indices.size(); i += 3)
        {
            const uint32_t index0 = component.indices.at(i + 0) + 1;
            const uint32_t index1 = component.indices.at(i + 1) + 1;
            const uint32_t index2 = component.indices.at(i + 2) + 1;
            file << std::format("f {0}/{0}/{0} {1}/{1}/{1} {2}/{2}/{2}\n", index0, index1, index2);
        }
        file << "\n";
    }

    file.close();
}

void ModelLod::Write(DataWriter &writer) const
{
    writer.Write<float>(distance);
    writer.Write<float>(distance * distance);
    writer.Write<float>(unitsPerLuxel);
    writer.Write<uint32_t>(lightmapSize.x);
    writer.Write<uint32_t>(lightmapSize.y);
    writer.Write<size_t>(vertices.size());
    for (const ModelVertex &vertex: vertices)
    {
        vertex.Write(writer);
    }
    writer.Write<uint32_t>(totalIndexCount);
    for (const ModelComponent &component: components)
    {
        writer.Write<uint32_t>(component.indices.size());
        writer.WriteBuffer<uint32_t>(component.indices);
        writer.WriteVec3(component.centerOffset);
        writer.Write<float>(component.radius);
    }
}

bool ModelLod::CalculateLightmapUvs()
{
    std::vector<stbrp_rect> rects{};
    for (const ModelComponent &component: components)
    {
        const std::vector<uint32_t> &indices = component.indices;
        for (uint32_t i = 0; i < component.indices.size(); i += 3)
        {
            const glm::vec3 &v1 = vertices.at(indices.at(i + 0)).position;
            const glm::vec3 &v2 = vertices.at(indices.at(i + 1)).position;
            const glm::vec3 &v3 = vertices.at(indices.at(i + 2)).position;

            const float a = glm::distance(v1, v2);
            const float b = glm::distance(v1, v3);
            const float c = glm::distance(v2, v3);

            assert(std::abs(c) > FLT_EPSILON);

            rects.emplace_back(0,
                               2 * LightmapHelpers::LIGHTMAP_PADDING + std::max(c, (b * b + c * c - a * a) / (2 * c)),
                               2 * LightmapHelpers::LIGHTMAP_PADDING +
                                       b * std::sin(std::acos((b * b + c * c - a * a) / (2 * b * c))));
        }
    }

    glm::uvec2 lightmapSize{};
    if (!LightmapHelpers::FitLightmap(rects, lightmapSize))
    {
        return false;
    }

    for (const ModelComponent &component: components)
    {
        const std::vector<uint32_t> &indices = component.indices;
        for (uint32_t i = 0; i < component.indices.size(); i += 3)
        {
            const stbrp_rect &rect = rects.at(i / 3);

            ModelVertex &v1 = vertices.at(indices.at(i + 0));
            ModelVertex &v2 = vertices.at(indices.at(i + 1));
            ModelVertex &v3 = vertices.at(indices.at(i + 2));

            const float a = glm::distance(v1.position, v2.position);
            const float b = glm::distance(v1.position, v3.position);
            const float c = glm::distance(v2.position, v3.position);

            v1.lightmapUv = LightmapHelpers::GetUv(lightmapSize, rect, {0, 0});
            v2.lightmapUv = LightmapHelpers::GetUv(lightmapSize, rect, {c, 0});
            v3.lightmapUv = LightmapHelpers::GetUv(lightmapSize,
                                                   rect,
                                                   {
                                                       (b * b + c * c - a * a) / (2 * c),
                                                       b * std::sin(std::acos((b * b + c * c - a * a) / (2 * b * c))),
                                                   });
        }
    }

    return true;
}

void ModelLod::FlipVerticalUVs()
{
    for (ModelVertex &v: vertices)
    {
        v.uv.y = 1.0f - v.uv.y;
    }
}
