//
// Created by droc101 on 7/16/25.
//

#ifndef LEVELASSET_H
#define LEVELASSET_H
#include <cstdint>
#include <vector>
#include <libassets/util/AssetReader.h>


// This is currently just a wrapper to compile & decompile BIN fies generated by geditor.
class LevelAsset
{
    public:
        LevelAsset() = default;

        [[nodiscard]] static Error::ErrorCode CreateFromAsset(const char *assetPath, LevelAsset &level);

        [[nodiscard]] static Error::ErrorCode CreateFromBin(const char *binPath, LevelAsset &level);

        [[nodiscard]] Error::ErrorCode SaveAsBin(const char *binPath) const;

        [[nodiscard]] Error::ErrorCode SaveAsAsset(const char *assetPath) const;

        [[nodiscard]] const std::vector<uint8_t> &GetData() const;

        [[nodiscard]] size_t GetDataSize() const;

        static constexpr uint8_t LEVEL_ASSET_VERSION = 1;

    private:
        std::vector<uint8_t> levelData;

        void SaveToBuffer(std::vector<uint8_t> &buffer) const;
};


#endif //LEVELASSET_H
