//
// Created by droc101 on 7/16/25.
//

#ifndef LEVELASSET_H
#define LEVELASSET_H
#include <cstdint>
#include <vector>


// This is currently just a wrapper to compile & decompile BIN fies generated by geditor.
class LevelAsset {
    public:
        LevelAsset() = default;

        [[nodiscard]] static LevelAsset CreateFromAsset(const char *assetPath);

        [[nodiscard]] static LevelAsset CreateFromBin(const char *binPath);

        void SaveAsBin(const char *binPath) const;

        void SaveAsAsset(const char *assetPath) const;

        [[nodiscard]] const std::vector<uint8_t> &GetData() const;
        [[nodiscard]] size_t GetDataSize() const;

    private:
        std::vector<uint8_t> levelData;

        void SaveToBuffer(std::vector<uint8_t> &buffer) const;
};



#endif //LEVELASSET_H
